# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3uwJlv7SW8JgEGcolusRqaHZ9ow6Xwv
"""

import random

# ---------------- PLAYER CLASS ----------------
class Player:
    def __init__(self):
        self.health = 100
        self.inventory = []

    def show_status(self):
        print(f"\n❤️ Health: {self.health}")
        print(f"🎒 Inventory: {self.inventory}")


# ---------------- GAME WORLD ----------------
rooms = {
    "Entrance": {"east": "Hallway", "item": None},
    "Hallway": {"west": "Entrance", "east": "Armory", "enemy": "Goblin"},
    "Armory": {"west": "Hallway", "south": "Treasure Room", "item": "Sword"},
    "Treasure Room": {"north": "Armory", "item": "Key"},
}

current_room = "Entrance"
player = Player()


# ---------------- COMBAT ----------------
def fight_enemy(enemy):
    print(f"\n⚔️ A {enemy} attacks!")

    enemy_health = 40

    while enemy_health > 0 and player.health > 0:
        action = input("Attack or Run? ").lower()

        if action == "attack":
            damage = random.randint(10, 25)
            enemy_damage = random.randint(5, 15)

            enemy_health -= damage
            player.health -= enemy_damage

            print(f"You hit {enemy} for {damage}")
            print(f"{enemy} hits you for {enemy_damage}")

        elif action == "run":
            print("You escaped!")
            return False
        else:
            print("Invalid action")

    if player.health <= 0:
        print("💀 You died!")
        return True

    print(f"✅ You defeated the {enemy}")
    return True


# ---------------- GAME LOOP ----------------
def game():
    global current_room

    print("🏰 Welcome to Dungeon Escape!")
    print("Find the KEY and return to Entrance to escape!")

    while True:
        print(f"\n📍 You are in: {current_room}")
        room_data = rooms[current_room]

        player.show_status()

        # Enemy encounter
        if "enemy" in room_data:
            defeated = fight_enemy(room_data["enemy"])
            if defeated:
                del room_data["enemy"]

        # Item pickup
        if room_data.get("item"):
            item = room_data["item"]
            take = input(f"You see a {item}. Take it? (yes/no): ").lower()
            if take == "yes":
                player.inventory.append(item)
                print(f"{item} added to inventory!")
                room_data["item"] = None

        # Escape condition
        if current_room == "Entrance" and "Key" in player.inventory:
            print("\n🎉 You unlocked the dungeon and escaped!")
            break

        move = input("Where do you want to go? ").lower()

        if move in room_data:
            current_room = room_data[move]
        else:
            print("🚫 You can't go that way!")

        if player.health <= 0:
            print("\nGame Over!")
            break


# ---------------- START GAME ----------------
game()

