# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBOFSE5BvNNKMqlp4Ue4N0rOczMssyza
"""

import random

def choose_difficulty():
    print("\nChoose Difficulty Level:")
    print("1. Easy (1-50, 10 attempts)")
    print("2. Medium (1-100, 7 attempts)")
    print("3. Hard (1-200, 5 attempts)")

    while True:
        choice = input("Enter 1, 2, or 3: ")
        if choice == "1":
            return 50, 10
        elif choice == "2":
            return 100, 7
        elif choice == "3":
            return 200, 5
        else:
            print("Invalid choice. Try again.")

def play_game():
    max_number, attempts = choose_difficulty()
    secret_number = random.randint(1, max_number)
    score = 100

    print(f"\nI have selected a number between 1 and {max_number}.")
    print(f"You have {attempts} attempts to guess it!")

    while attempts > 0:
        try:
            guess = int(input("\nEnter your guess: "))
        except ValueError:
            print("Please enter a valid number.")
            continue

        if guess == secret_number:
            print("Correct! You guessed it!")
            print(f"Your score: {score}")
            return score
        elif guess < secret_number:
            print("Too low!")
        else:
            print("Too high!")

        attempts -= 1
        score -= 10
        print(f"Attempts left: {attempts}")

    print(f"Game Over! The number was {secret_number}")
    return 0

def main():
    total_score = 0

    while True:
        total_score += play_game()
        print(f"\nTotal Score: {total_score}")

        again = input("\nDo you want to play again? (yes/no): ").lower()
        if again != "yes":
            print("Thanks for playing!")
            break

main()

