# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mJvvAIwS-JBGTY_8ZTkfsfaAUFcl3z6
"""

import random

choices = ["rock", "paper", "scissors"]

def decide_winner(player, computer):
    if player == computer:
        return "It's a tie!"
    elif (player == "rock" and computer == "scissors") or \
         (player == "paper" and computer == "rock") or \
         (player == "scissors" and computer == "paper"):
        return "You win!"
    else:
        return "Computer wins!"

print("----- Rock Paper Scissors Game -----")
print("Type 'quit' anytime to stop.\n")

while True:
    player_choice = input("Choose rock, paper, or scissors: ").lower()

    if player_choice == "quit":
        print("Thanks for playing!")
        break

    if player_choice not in choices:
        print("Invalid choice. Try again.")
        continue

    computer_choice = random.choice(choices)

    print("You chose:", player_choice)
    print("Computer chose:", computer_choice)
    print(decide_winner(player_choice, computer_choice))
    print("-" * 30)

